// ==================== config/campaignTypes.ts ====================
import {
  Mail,
  Smartphone,
  FileText,
  GraduationCap,
  BookOpen,
} from "lucide-react";
import { CampaignType } from "../types/billing.types";

export const CAMPAIGN_TYPES: Record<string, CampaignType> = {
  email: {
    id: "email",
    label: "Email Campaigns",
    icon: Mail,
    plans: {
      Basic: {
        name: "Basic",
        price: 170000,
        dailyLimit: 5000,
        monthlyLimit: 150000,
        contactLimit: 5000,
        userLimit: 1,
        scheduleLimit: 5,
        features: [
          "5,000 emails/day",
          "5,000 contacts",
          "1 user account",
          "5 schedules",
          "Basic templates",
          "Email support",
        ],
      },
      Growth: {
        name: "Growth",
        price: 280000,
        dailyLimit: 10000,
        monthlyLimit: 300000,
        contactLimit: 10000,
        userLimit: 2,
        scheduleLimit: 12,
        features: [
          "10,000 emails/day",
          "10,000 contacts",
          "2 user accounts",
          "12 schedules",
          "All templates",
          "Chat support",
        ],
      },
      Pro: {
        name: "Pro",
        price: 450000,
        dailyLimit: 25000,
        monthlyLimit: 750000,
        contactLimit: 25000,
        userLimit: 3,
        scheduleLimit: 30,
        features: [
          "25,000 emails/day",
          "25,000 contacts",
          "3 user accounts",
          "30 schedules",
          "Premium templates",
          "Priority support",
        ],
      },
      Enterprise: {
        name: "Enterprise",
        price: 650000,
        dailyLimit: 50000,
        monthlyLimit: 1500000,
        contactLimit: 50000,
        userLimit: 5,
        scheduleLimit: null,
        features: [
          "50,000+ emails/day",
          "50,000+ contacts",
          "5+ user accounts",
          "Unlimited schedules",
          "Custom templates",
          "Dedicated support",
        ],
      },
    },
  },
  quills: {
    id: "quills",
    label: "Quills Ads",
    icon: Smartphone,
    plans: {
      Basic: {
        name: "Basic",
        price: 150000,
        dailyLimit: 3000,
        monthlyLimit: 90000,
        impressionLimit: 50000,
        userLimit: 1,
        scheduleLimit: 3,
        features: [
          "3,000 ads/day",
          "50,000 impressions/month",
          "1 user account",
          "3 schedules",
          "Standard placements",
          "Email support",
        ],
      },
      Growth: {
        name: "Growth",
        price: 250000,
        dailyLimit: 7000,
        monthlyLimit: 210000,
        impressionLimit: 150000,
        userLimit: 2,
        scheduleLimit: 10,
        features: [
          "7,000 ads/day",
          "150,000 impressions/month",
          "2 user accounts",
          "10 schedules",
          "Premium placements",
          "Chat support",
        ],
      },
      Pro: {
        name: "Pro",
        price: 400000,
        dailyLimit: 15000,
        monthlyLimit: 450000,
        impressionLimit: 500000,
        userLimit: 3,
        scheduleLimit: 25,
        features: [
          "15,000 ads/day",
          "500,000 impressions/month",
          "3 user accounts",
          "25 schedules",
          "Priority placements",
          "Priority support",
        ],
      },
      Enterprise: {
        name: "Enterprise",
        price: 600000,
        dailyLimit: 30000,
        monthlyLimit: 900000,
        impressionLimit: 1000000,
        userLimit: 5,
        scheduleLimit: null,
        features: [
          "30,000+ ads/day",
          "1M+ impressions/month",
          "5+ user accounts",
          "Unlimited schedules",
          "Custom placements",
          "Dedicated support",
        ],
      },
    },
  },
  blog: {
    id: "blog",
    label: "Blog Ads",
    icon: FileText,
    plans: {
      Basic: {
        name: "Basic",
        price: 120000,
        dailyLimit: 2000,
        monthlyLimit: 60000,
        postLimit: 100,
        userLimit: 1,
        scheduleLimit: 5,
        features: [
          "2,000 ads/day",
          "100 blog posts",
          "1 user account",
          "5 schedules",
          "Standard visibility",
          "Email support",
        ],
      },
      Growth: {
        name: "Growth",
        price: 220000,
        dailyLimit: 5000,
        monthlyLimit: 150000,
        postLimit: 300,
        userLimit: 2,
        scheduleLimit: 12,
        features: [
          "5,000 ads/day",
          "300 blog posts",
          "2 user accounts",
          "12 schedules",
          "Enhanced visibility",
          "Chat support",
        ],
      },
      Pro: {
        name: "Pro",
        price: 350000,
        dailyLimit: 10000,
        monthlyLimit: 300000,
        postLimit: 1000,
        userLimit: 3,
        scheduleLimit: 20,
        features: [
          "10,000 ads/day",
          "1,000 blog posts",
          "3 user accounts",
          "20 schedules",
          "Priority visibility",
          "Priority support",
        ],
      },
      Enterprise: {
        name: "Enterprise",
        price: 550000,
        dailyLimit: 20000,
        monthlyLimit: 600000,
        postLimit: null,
        userLimit: 5,
        scheduleLimit: null,
        features: [
          "20,000+ ads/day",
          "Unlimited blog posts",
          "5+ user accounts",
          "Unlimited schedules",
          "Featured visibility",
          "Dedicated support",
        ],
      },
    },
  },
  scholarship: {
    id: "scholarship",
    label: "Scholarship Ads",
    icon: GraduationCap,
    plans: {
      Basic: {
        name: "Basic",
        price: 100000,
        dailyLimit: 1000,
        monthlyLimit: 30000,
        listingLimit: 50,
        userLimit: 1,
        scheduleLimit: 3,
        features: [
          "1,000 ads/day",
          "50 scholarship listings",
          "1 user account",
          "3 schedules",
          "Standard reach",
          "Email support",
        ],
      },
      Growth: {
        name: "Growth",
        price: 200000,
        dailyLimit: 3000,
        monthlyLimit: 90000,
        listingLimit: 150,
        userLimit: 2,
        scheduleLimit: 8,
        features: [
          "3,000 ads/day",
          "150 scholarship listings",
          "2 user accounts",
          "8 schedules",
          "Enhanced reach",
          "Chat support",
        ],
      },
      Pro: {
        name: "Pro",
        price: 320000,
        dailyLimit: 7000,
        monthlyLimit: 210000,
        listingLimit: 500,
        userLimit: 3,
        scheduleLimit: 15,
        features: [
          "7,000 ads/day",
          "500 scholarship listings",
          "3 user accounts",
          "15 schedules",
          "Priority reach",
          "Priority support",
        ],
      },
      Enterprise: {
        name: "Enterprise",
        price: 500000,
        dailyLimit: 15000,
        monthlyLimit: 450000,
        listingLimit: null,
        userLimit: 5,
        scheduleLimit: null,
        features: [
          "15,000+ ads/day",
          "Unlimited listings",
          "5+ user accounts",
          "Unlimited schedules",
          "Maximum reach",
          "Dedicated support",
        ],
      },
    },
  },
  library: {
    id: "library",
    label: "Library Ads",
    icon: BookOpen,
    plans: {
      Basic: {
        name: "Basic",
        price: 90000,
        dailyLimit: 800,
        monthlyLimit: 24000,
        bookLimit: 100,
        userLimit: 1,
        scheduleLimit: 3,
        features: [
          "800 ads/day",
          "100 books/resources",
          "1 user account",
          "3 schedules",
          "Basic catalog",
          "Email support",
        ],
      },
      Growth: {
        name: "Growth",
        price: 180000,
        dailyLimit: 2000,
        monthlyLimit: 60000,
        bookLimit: 300,
        userLimit: 2,
        scheduleLimit: 8,
        features: [
          "2,000 ads/day",
          "300 books/resources",
          "2 user accounts",
          "8 schedules",
          "Enhanced catalog",
          "Chat support",
        ],
      },
      Pro: {
        name: "Pro",
        price: 300000,
        dailyLimit: 5000,
        monthlyLimit: 150000,
        bookLimit: 1000,
        userLimit: 3,
        scheduleLimit: 15,
        features: [
          "5,000 ads/day",
          "1,000 books/resources",
          "3 user accounts",
          "15 schedules",
          "Premium catalog",
          "Priority support",
        ],
      },
      Enterprise: {
        name: "Enterprise",
        price: 480000,
        dailyLimit: 10000,
        monthlyLimit: 300000,
        bookLimit: null,
        userLimit: 5,
        scheduleLimit: null,
        features: [
          "10,000+ ads/day",
          "Unlimited resources",
          "5+ user accounts",
          "Unlimited schedules",
          "Custom catalog",
          "Dedicated support",
        ],
      },
    },
  },
};
